project_id = "vektor-go"

[functions.mp-authorize]
verify_jwt = false

[functions.mp-callback]
verify_jwt = false

[functions.create-subscription]
verify_jwt = false

[functions.subscription-callback]
verify_jwt = false
